/* ============================================================
 * SIMPL → LLVM IR Code Generator
 * ============================================================ */

#include "codegen.h"
#include "../optimizer/optimizer.h"   /* is_dead() */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============================================================
 * SECTION 1 — UTILITY HELPERS
 * ============================================================ */

/* Return 1 if the string is a decimal integer literal. */
static int is_literal(const char *s) {
    if (!s || s[0] == '\0') return 0;
    int i = 0;
    if (s[i] == '-') i++;
    if (s[i] == '\0') return 0;
    for (; s[i]; i++)
        if (s[i] < '0' || s[i] > '9') return 0;
    return 1;
}

/* Return 1 if the name looks like a compiler temp (t0, t1, …). */
static int is_temp(const char *s) {
    if (!s || s[0] != 't') return 0;
    for (int i = 1; s[i]; i++)
        if (s[i] < '0' || s[i] > '9') return 0;
    return s[1] != '\0';
}

/* Track which user variables have been alloca'd. */
static int var_is_allocated(CodegenCtx *ctx, const char *name) {
    for (int i = 0; i < ctx->var_count; i++)
        if (strcmp(ctx->vars[i], name) == 0) return 1;
    return 0;
}

static void var_register(CodegenCtx *ctx, const char *name) {
    if (!var_is_allocated(ctx, name) && ctx->var_count < 128) {
        strncpy(ctx->vars[ctx->var_count++], name, 31);
    }
}

/* ── Value helper ──────────────────────────────────────────
 * Produce the LLVM "value string" for a SIMPL operand:
 *   - integer literal  → the literal itself  (e.g. "42")
 *   - compiler temp    → %tN                 (SSA register)
 *   - user variable    → load from alloca    (emits a load)
 *
 * When the operand is a user variable, this function emits
 * a load instruction and returns a fresh anonymous register
 * name that the caller can use as an operand.
 *
 * `reg_buf` must be at least 32 bytes.
 * Returns a pointer to either `operand` (literal/temp) or
 * `reg_buf` (freshly loaded user variable). */
static const char *emit_operand(CodegenCtx *ctx,
                                const char *operand,
                                char       *reg_buf) {
    if (is_literal(operand)) {
        return operand;                   /* plain integer constant */
    }
    if (is_temp(operand)) {
        snprintf(reg_buf, 32, "%%%s", operand);
        return reg_buf;                   /* already an SSA reg */
    }
    /* User variable — emit a load */
    int reg = ctx->reg_counter++;
    fprintf(ctx->out, "  %%r%d = load i32, i32* %%%s_slot, align 4\n",
            reg, operand);
    snprintf(reg_buf, 32, "%%r%d", reg);
    return reg_buf;
}

/* ============================================================
 * SECTION 2 — FIRST PASS: COLLECT ALL USER VARIABLES
 *
 * We need to emit alloca instructions for every user variable
 * at the top of the entry block before any other instructions.
 * Walk the whole IR list once to collect names.
 * ============================================================ */

static void collect_variables(CodegenCtx *ctx, IRInstruction *ir_head) {
    IRInstruction *inst = ir_head;
    while (inst) {
        /* result field of ASSIGN is a user variable write */
        if (inst->op == IR_ASSIGN && !is_temp(inst->result)) {
            var_register(ctx, inst->result);
        }
        inst = inst->next;
    }
}

/* ============================================================
 * SECTION 3 — MODULE HEADER
 * ============================================================ */

static void emit_module_header(CodegenCtx *ctx) {
    fprintf(ctx->out,
        "; ============================================================\n"
        "; SIMPL Compiled Output — LLVM IR\n"
        "; Generated by the SIMPL compiler\n"
        "; Compile with:  clang output.ll -o program\n"
        "; ============================================================\n"
        "\n"
        "target triple = \"x86_64-pc-linux-gnu\"\n"
        "\n"
        "; printf format string for print statements\n"
        "@fmt = private unnamed_addr constant [4 x i8] c\"%%d\\0A\\00\"\n"
        "\n"
        "declare i32 @printf(i8*, ...)\n"
        "\n"
    );
}

/* ============================================================
 * SECTION 4 — ALLOCA BLOCK
 *
 * Every user variable gets its own i32 stack slot in the
 * function entry block.  LLVM's mem2reg pass will promote
 * these to SSA registers during optimisation.
 * ============================================================ */

static void emit_allocas(CodegenCtx *ctx) {
    for (int i = 0; i < ctx->var_count; i++) {
        fprintf(ctx->out,
            "  %%%s_slot = alloca i32, align 4\n", ctx->vars[i]);
    }
    if (ctx->var_count > 0) fprintf(ctx->out, "\n");
}

/* ============================================================
 * SECTION 5 — INSTRUCTION EMITTER
 *
 * Maps each SIMPL IR opcode to one or more LLVM instructions.
 * ============================================================ */

/* Emit a binary arithmetic instruction. */
static void emit_binop(CodegenCtx *ctx,
                       const char *llvm_op,
                       IRInstruction *inst) {
    char buf_a[32], buf_b[32];
    const char *a = emit_operand(ctx, inst->arg1, buf_a);
    const char *b = emit_operand(ctx, inst->arg2, buf_b);
    fprintf(ctx->out, "  %%%s = %s i32 %s, %s\n",
            inst->result, llvm_op, a, b);
}

/* Emit an icmp + zext for a SIMPL comparison.
 * LLVM icmp returns i1; we zero-extend to i32 so the result
 * can feed arithmetic or a branch condition. */
static void emit_cmp(CodegenCtx *ctx, IRInstruction *inst) {
    const char *pred = NULL;
    switch (inst->cmp_op) {
        case '>': pred = "sgt"; break;
        case '<': pred = "slt"; break;
        case '=': pred = "eq";  break;
        case '!': pred = "ne";  break;
        default:
            fprintf(stderr, "[CG] Unknown cmp_op '%c'\n", inst->cmp_op);
            pred = "eq";
    }

    char buf_a[32], buf_b[32];
    const char *a = emit_operand(ctx, inst->arg1, buf_a);
    const char *b = emit_operand(ctx, inst->arg2, buf_b);

    /* icmp gives i1, zext promotes to i32 (0 or 1) */
    int cmp_reg = ctx->reg_counter++;
    fprintf(ctx->out,
        "  %%cmp%d = icmp %s i32 %s, %s\n"
        "  %%%s = zext i1 %%cmp%d to i32\n",
        cmp_reg, pred, a, b,
        inst->result, cmp_reg);
}

/* Emit IR_ASSIGN: either store to a user variable slot,
 * or copy to an SSA temp with add ... 0. */
static void emit_assign(CodegenCtx *ctx, IRInstruction *inst) {
    char buf[32];
    const char *src = emit_operand(ctx, inst->arg1, buf);

    if (is_temp(inst->result)) {
        /* temp = value  →  %tN = add i32 <src>, 0  (identity copy) */
        fprintf(ctx->out, "  %%%s = add i32 %s, 0\n",
                inst->result, src);
    } else {
        /* user variable — store into its alloca slot */
        fprintf(ctx->out, "  store i32 %s, i32* %%%s_slot, align 4\n",
                src, inst->result);
    }
}

/* Emit IR_PRINT: call printf("%d\n", value). */
static void emit_print(CodegenCtx *ctx, IRInstruction *inst) {
    char buf[32];
    const char *val = emit_operand(ctx, inst->result, buf);
    int gep_reg = ctx->reg_counter++;
    fprintf(ctx->out,
        "  %%gep%d = getelementptr [4 x i8], [4 x i8]* @fmt, i32 0, i32 0\n"
        "  call i32 (i8*, ...) @printf(i8* %%gep%d, i32 %s)\n",
        gep_reg, gep_reg, val);
}

/* Emit IR_LABEL: close the previous block with a fallthrough
 * branch (if the block doesn't already end with a terminator),
 * then open the new block. */
static void emit_label(CodegenCtx *ctx, IRInstruction *inst,
                       IRInstruction *prev_inst) {
    /* Insert a fallthrough branch to this label from the
     * previous block, unless the previous instruction was
     * already a terminator (goto / if_false_goto). */
    int prev_was_terminator = prev_inst &&
        (prev_inst->op == IR_GOTO || prev_inst->op == IR_IF_FALSE_GOTO);

    if (!prev_was_terminator) {
        fprintf(ctx->out, "  br label %%%s\n", inst->result);
    }
    fprintf(ctx->out, "\n%s:\n", inst->result);
    strncpy(ctx->current_label, inst->result, 31);
}

/* Emit IR_GOTO: unconditional branch. */
static void emit_goto(CodegenCtx *ctx, IRInstruction *inst) {
    fprintf(ctx->out, "  br label %%%s\n", inst->result);
}

/* Emit IR_IF_FALSE_GOTO: conditional branch.
 *
 * SIMPL semantics: if the condition value is 0 (false), jump.
 * LLVM needs an i1 condition for br.
 *
 *   %condN = icmp ne i32 <cond>, 0     ; true if cond != 0
 *   br i1 %condN, label %fallthrough, label %target
 */
static void emit_if_false_goto(CodegenCtx *ctx,
                               IRInstruction *inst,
                               IRInstruction *next_inst) {
    char buf[32];
    const char *cond = emit_operand(ctx, inst->arg1, buf);
    int cond_reg = ctx->reg_counter++;

    /* Determine fallthrough label.  If next instruction is a
     * LABEL we can use it directly; otherwise synthesise one. */
    char fallthrough[32];
    if (next_inst && next_inst->op == IR_LABEL) {
        strncpy(fallthrough, next_inst->result, 31);
    } else {
        /* Generate an inline fallthrough label */
        snprintf(fallthrough, sizeof(fallthrough), "ft%d", cond_reg);
    }

    fprintf(ctx->out,
        "  %%cond%d = icmp ne i32 %s, 0\n"
        "  br i1 %%cond%d, label %%%s, label %%%s\n",
        cond_reg, cond,
        cond_reg, fallthrough, inst->result);

    /* If we synthesised a fallthrough label, emit it now. */
    if (!(next_inst && next_inst->op == IR_LABEL)) {
        fprintf(ctx->out, "\n%s:\n", fallthrough);
    }
}

/* ============================================================
 * SECTION 6 — MAIN EMISSION LOOP
 * ============================================================ */

static void emit_instructions(CodegenCtx *ctx, IRInstruction *ir_head) {
    IRInstruction *inst = ir_head;
    IRInstruction *prev = NULL;

    while (inst) {
        /* Skip dead instructions from the optimizer */
        if (is_dead(inst)) {
            prev = inst;
            inst = inst->next;
            continue;
        }

        switch (inst->op) {
            case IR_ASSIGN:
                emit_assign(ctx, inst);
                break;

            case IR_ADD:
                emit_binop(ctx, "add",  inst);
                break;
            case IR_SUB:
                emit_binop(ctx, "sub",  inst);
                break;
            case IR_MUL:
                emit_binop(ctx, "mul",  inst);
                break;
            case IR_DIV:
                emit_binop(ctx, "sdiv", inst);
                break;

            case IR_CMP:
                emit_cmp(ctx, inst);
                break;

            case IR_PRINT:
                emit_print(ctx, inst);
                break;

            case IR_LABEL:
                emit_label(ctx, inst, prev);
                break;

            case IR_GOTO:
                emit_goto(ctx, inst);
                break;

            case IR_IF_FALSE_GOTO:
                emit_if_false_goto(ctx, inst, inst->next);
                break;
        }

        prev = inst;
        inst = inst->next;
    }
}

/* ============================================================
 * SECTION 7 — PUBLIC ENTRY POINT
 * ============================================================ */

int codegen_emit_llvm(IRInstruction *ir_head, const char *out_path) {
    FILE *out = fopen(out_path, "w");
    if (!out) {
        perror(out_path);
        return -1;
    }

    CodegenCtx ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.out         = out;
    ctx.reg_counter = 0;
    strncpy(ctx.current_label, "entry", 31);

    /* ── Step 1: module header (target triple, @fmt, printf decl) */
    emit_module_header(&ctx);

    /* ── Step 2: scan IR to collect all user variable names */
    collect_variables(&ctx, ir_head);

    /* ── Step 3: open define @main */
    fprintf(out,
        "define i32 @main() {\n"
        "entry:\n"
    );

    /* ── Step 4: emit alloca for every user variable */
    emit_allocas(&ctx);

    /* ── Step 5: emit the instruction stream */
    emit_instructions(&ctx, ir_head);

    /* ── Step 6: close @main */
    fprintf(out,
        "\n"
        "  ret i32 0\n"
        "}\n"
    );

    fclose(out);
    printf("[CG] LLVM IR written to: %s\n", out_path);
    printf("[CG] Compile with: clang %s -o program\n", out_path);
    return 0;
}
